# Generated by Django 5.2.7 on 2025-11-11 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoVehiculo',
            fields=[
                ('id_estado_vehiculo', models.AutoField(db_column='id_estado_vehiculo', primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Estado del Vehículo',
                'verbose_name_plural': 'Estados del Vehículo',
                'db_table': 'Seguridad_estado_vehiculo',
            },
        ),
        migrations.RenameField(
            model_name='documentosolicitud',
            old_name='tamaño_archivo',
            new_name='tamano_archivo',
        ),
        migrations.RemoveField(
            model_name='vehiculos',
            name='estado_vehiculo',
        ),
        migrations.AddField(
            model_name='asignacionvehiculo',
            name='kilometraje_inicial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignacionvehiculo',
            name='kilometraje_recorrido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignacionvehiculo',
            name='kilometraje_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='total_kilometraje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignacionderivacionemergencia',
            name='id_derivacion',
            field=models.ForeignKey(db_column='id_derivacion', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.derivacionesdenuncia'),
        ),
        migrations.AlterField(
            model_name='asignacionderivacionemergencia',
            name='id_servicio',
            field=models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.serviciosemergencia'),
        ),
        migrations.AlterField(
            model_name='asignacionradio',
            name='id_radio',
            field=models.ForeignKey(db_column='id_radio', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.radio'),
        ),
        migrations.AlterField(
            model_name='asignacionradio',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacionvehiculo',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignacionvehiculo',
            name='id_vehiculo',
            field=models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.vehiculos'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='id_ciudadano',
            field=models.AutoField(db_column='id_ciudadano', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id_ciudadano',
            field=models.ForeignKey(db_column='id_ciudadano', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.ciudadano'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id_denuncia',
            field=models.AutoField(db_column='id_denuncia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id_requerimiento',
            field=models.ForeignKey(db_column='id_requerimiento', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.requerimiento'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='derivacionesdenuncia',
            name='id_conductor',
            field=models.ForeignKey(blank=True, db_column='id_conductor', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='derivacionesdenuncia',
            name='id_denuncia',
            field=models.ForeignKey(db_column='id_denuncia', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.denuncia'),
        ),
        migrations.AlterField(
            model_name='derivacionesdenuncia',
            name='id_derivacion',
            field=models.AutoField(db_column='id_derivacion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='derivacionesdenuncia',
            name='id_servicio',
            field=models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.PROTECT, to='Seguridad.serviciosemergencia'),
        ),
        migrations.AlterField(
            model_name='documentosolicitud',
            name='id_documento',
            field=models.AutoField(db_column='id_documento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentosolicitud',
            name='id_solicitud',
            field=models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.solicitudciudadano'),
        ),
        migrations.AlterField(
            model_name='familiadenuncia',
            name='id_familia_denuncia',
            field=models.AutoField(db_column='id_familia_denuncia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalizacion',
            name='id_fiscalizacion',
            field=models.AutoField(db_column='id_fiscalizacion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalizacion',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupodenuncia',
            name='id_familia_denuncia',
            field=models.ForeignKey(db_column='id_familia_denuncia', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.familiadenuncia'),
        ),
        migrations.AlterField(
            model_name='grupodenuncia',
            name='id_grupo_denuncia',
            field=models.AutoField(db_column='id_grupo_denuncia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movilesdenuncia',
            name='id_conductor',
            field=models.ForeignKey(db_column='id_conductor', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movilesdenuncia',
            name='id_denuncia',
            field=models.ForeignKey(db_column='id_denuncia', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.denuncia'),
        ),
        migrations.AlterField(
            model_name='movilesdenuncia',
            name='id_movil_denuncia',
            field=models.AutoField(db_column='id_movil_denuncia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movilesdenuncia',
            name='id_vehiculo',
            field=models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.vehiculos'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='id_radio',
            field=models.AutoField(db_column='id_radio', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='id_requerimiento',
            field=models.AutoField(db_column='id_requerimiento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='id_subgrupo_denuncia',
            field=models.ForeignKey(db_column='id_subgrupo_denuncia', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.subgrupodenuncia'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='id_rol',
            field=models.AutoField(db_column='id_rol', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviciosemergencia',
            name='id_servicio',
            field=models.AutoField(db_column='id_servicio', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudciudadano',
            name='id_ciudadano',
            field=models.ForeignKey(db_column='id_ciudadano', on_delete=django.db.models.deletion.CASCADE, to='Seguridad.ciudadano'),
        ),
        migrations.AlterField(
            model_name='solicitudciudadano',
            name='id_solicitud',
            field=models.AutoField(db_column='id_solicitud', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajador',
            name='estado_solicitud_trabajador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajador',
            name='id_solicitud_trabajador',
            field=models.AutoField(db_column='id_solicitud_trabajador', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajador',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subgrupodenuncia',
            name='id_grupo_denuncia',
            field=models.ForeignKey(db_column='id_grupo_denuncia', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.grupodenuncia'),
        ),
        migrations.AlterField(
            model_name='subgrupodenuncia',
            name='id_subgrupo_denuncia',
            field=models.AutoField(db_column='id_subgrupo_denuncia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiposvehiculos',
            name='id_tipo_vehiculo',
            field=models.AutoField(db_column='id_tipo_vehiculo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='id_turno',
            field=models.AutoField(db_column='id_turno', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico_usuario',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.roles'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_turno',
            field=models.ForeignKey(blank=True, db_column='id_turno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seguridad.turnos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(db_column='id_usuario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut_usuario',
            field=models.CharField(help_text='Formato: 12345678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato: 12345678-9', regex='^\\d{7,8}-[\\dkK]$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_movil_usuario',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener formato: +56912345678', regex='^\\+?56?9?\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='id_tipo_vehiculo',
            field=models.ForeignKey(db_column='id_tipo_vehiculo', on_delete=django.db.models.deletion.PROTECT, to='Seguridad.tiposvehiculos'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='id_vehiculo',
            field=models.AutoField(db_column='id_vehiculo', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='id_estado_vehiculo',
            field=models.ForeignKey(db_column='id_estado_vehiculo', default=1, on_delete=django.db.models.deletion.PROTECT, to='Seguridad.estadovehiculo'),
            preserve_default=False,
        ),
    ]
