# Generated by Django 5.2.7 on 2025-11-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0003_estadovehiculo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudadano',
            old_name='contraseña_ciudadano',
            new_name='password_ciudadano',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='asignacionvehiculo',
            name='activo',
            field=models.SmallIntegerField(choices=[(1, 'Activo/Disponible'), (2, 'En Mantención')], default=1),
        ),
    ]
