# Generated by Django 5.2.7 on 2025-12-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0004_rename_contraseña_ciudadano_ciudadano_password_ciudadano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionvehiculo',
            name='id',
        ),
        migrations.AddField(
            model_name='asignacionvehiculo',
            name='id_asignacion_vehiculo',
            field=models.AutoField(db_column='id_asignacion_vehiculo', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='asignacionvehiculo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionradio',
            name='id',
            field=models.AutoField(db_column='id_asignacion_radio', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asignacionvehiculo',
            name='activo',
            field=models.SmallIntegerField(choices=[(1, 'Disponible'), (2, 'En proceso'), (3, 'En central'), (4, 'No disponible')], default=1),
        ),
    ]
