# Generated by Django 5.2.7 on 2025-12-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0005_remove_asignacionvehiculo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionradio',
            old_name='id',
            new_name='id_asignacion_radio',
        ),
    ]
