# Generated by Django 5.2.7 on 2025-12-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0006_rename_id_asignacionradio_id_asignacion_radio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionvehiculo',
            name='observaciones',
        ),
    ]
