# Generated by Django 5.2.7 on 2025-12-04 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0007_remove_asignacionvehiculo_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='nombre_denunciante',
            field=models.CharField(blank=True, default='', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='telefono_denunciante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DenunciaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='denuncias/')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Seguridad.denuncia')),
            ],
            options={
                'db_table': 'Seguridad_denuncia_imagen',
            },
        ),
    ]
